### ISSUE TITLE
Silacak 3.0 API Contract MVP

### ISSUE THREAD

**Issue by ramarahmanda** [kawalcovid19/silacak#20]
## Overview

This epic outlines the API contract for integration with https://github.com/kawalcovid19/silacak/issues/8

## Implementation Models
Use OpenAPI Standard yaml file

## Current Tasks

List of API 
- [ ] Login
- [ ] Register
- [ ] Check account activation
- [ ] List trace peoples
- [ ] Detail trace people
- [ ] Add close contact
- [ ] (test...)
