### ISSUE TITLE
Add close contact

### ISSUE THREAD

**Issue by ramarahmanda** [kawalcovid19/silacak#29]
## Description

This page contain a form to add close contact to people with a confirmed case. This page, redirected from button `+ Kontak Erat` in confirmed cases page.

Figma: https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=53%3A1045
Prototype: https://www.figma.com/proto/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=7%3A3802&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=4%3A2&hide-ui=1

## Tasks

- [ ] People with confirmed case profile
- [ ] Entry close contact profile using NIK or manual
- [ ] Entry whatsapp/phone number
- [ ] Contact time 
- [ ] Relationship with close contact
- [ ] Monitoring start - end

## Note

This page's functionality is **blocked** because of the absence of support from the existing backend.
Therefore, we consider it to be **low-priority**, including for the frontend-only implementation.

**Comment by saylhendra** [comment]
mas @zainfathoni, @resir014, this issue is open right ?, what's is mean by reference to #62 ? can i take it ?

**Comment by zainfathoni** [comment]
Based on #8, it's still blockedby the backend. So please prioritise the other unblocked issues @saylhendra, thanks!

**Comment by saylhendra** [comment]
i see, thanks mas.
