### ISSUE TITLE
Confirmed case

### ISSUE THREAD

**Issue by ramarahmanda** [kawalcovid19/silacak#30]
## Description

This page contains list of confirmed cases by _puskesmas_ . Each row in table represent people that has been confirmed for covid19 case (data from NAR). We can add close contact for each confirmed case or look confirmed case profile. 

Figma: https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=12%3A1594

## Tasks

- [ ] Selected _puskesmas_
- [ ] Id & Title _puskesmas_
- [ ] Tab to change to other list
- [ ] Filter/search confirmed case by nik & name
- [ ] Confirmed case table
