### ISSUE TITLE
Confirmed Case - Detail 

### ISSUE THREAD

**Issue by auliazahrina** [kawalcovid19/silacak#31]
## Description

This page contains detailed information of a confirmed case (data from NAR). It also contains **status** whether this confirmed case can be contacted or not (manually set by user, not implemented yet in current system). It also contains a list of related close contacts.

Figma: [(https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=130%3A1315)](url)

## Tasks

- [ ] Display confirmed case detail 
- [ ] Create "Confirmed Case Status" 
- [ ] "Add new close contact" button 
- [ ] Search close contact by name or HP 
- [ ] Related close contacts table
- [ ] Buttons "Tambah Pemantauan" and "Lihat Detil" on each row of close contacts
