### ISSUE TITLE
Confirmed Case - Detail

### ISSUE THREAD

**Issue by auliazahrina** [kawalcovid19/silacak#33]
## Description

This page contains detailed information of a confirmed case (data from NAR). It also contains **status** whether this confirmed case can be contacted or not (manually set by user, not implemented yet in current system). It also contains a list of related close contacts.

This page can be accessed after clicking "Lihat Detil" button on confirmed case list. 

Figma: [https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=130%3A1315](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=130%3A1315)
Prototype: https://www.figma.com/proto/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=130%3A1315&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=4%3A2&hide-ui=1

## Tasks

- [ ] Display confirmed case detail 
- [ ] Create "Confirmed Case Status" - [Status 1](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=214%3A2982) - [Status 2](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=214%3A3317)
- [ ] "Add new close contact" button 
- [ ] Search close contact by name or HP 
- [ ] Related close contacts table
- [ ] Buttons "Tambah Pemantauan" and "Lihat Detil" on each row of close contacts

**Comment by zainfathoni** [comment]
@all-contributors please add @auliazahrina for project management, docs, and ideas.

**Comment by resir014** [comment]
Blocked by #62.
