### ISSUE TITLE
Add Monitoring

### ISSUE THREAD

**Issue by auliazahrina** [kawalcovid19/silacak#35]
## Description

This page contains monitoring variables that can be added daily to a close contact. Details of each variable: 

**Jenis Karantina** 
- Tidak Karantina
- Karantina mandiri di rumah
- Karantina di fasilitas khusus --> if chosen, a text field "Nama lokasi karantina" appears 

**Hasil Pemantauan**
- Sehat
- Bergejala (suspek) --> if chosen, input options for symptoms appear
- Rujuk ke RS
- Meninggal --> if chosen, a date picker "Tanggal meninggal" appears 

Figma: [https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=130%3A2211](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=130%3A2211)

## Tasks

- [ ] Display close contact detail 
- [ ] Set monitoring date as today (default) 
- [ ] Create options: Jenis Karantina 
- [ ] If Karantina di fasilitas khusus --> input Nama lokasi karantina 
- [ ] Create options: Hasil Pemantauan 
- [ ] If Meninggal --> input Tanggal meninggal
- [ ] If Bergejala (suspek) --> input symptoms

**Comment by resir014** [comment]
Blocked by #62.
