### ISSUE TITLE
Monitoring List

### ISSUE THREAD

**Issue by auliazahrina** [kawalcovid19/silacak#36]
## Description

This page contains a list of close contacts that should be monitored daily. 

Figma: [https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=143%3A2286](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=143%3A2286)
Prototype: https://www.figma.com/proto/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=143%3A2286&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=4%3A2&hide-ui=1

## Tasks

- [ ] Filter by Puskesmas, default show All Puskesmas 
- [ ] Search by name or HP 
- [ ] Active close contact case table 
- [ ] "Tambah pemantauan" and "Selesai Karantina" button on each close contact row

**Comment by resir014** [comment]
Blocked by #62.
