### ISSUE TITLE
End-to-end Tests Infrastructure

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/silacak#58]
## Overview

This project is very crucial, and we can't afford any regressions introduced in the coming changes.
Therefore, we have to introduce a proper infrastructure for end-to-end tests to guarantee that our changes don't introduce regressions in the future.

## References

You can refer to [this project](https://github.com/kentcdodds/jest-cypress-react-babel-webpack/blob/main/package.json) as an example.

## Current Tasks

- [ ] Install Cypress and setup the end-to-end test configurations
- [ ] Write an end-to-end test for the Provinces page search functionality
- [ ] Run end-to-end tests in the test.yml workflow
